repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: name-tests-test
        args: [ --pytest-test-first ]

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.17
    hooks:
    -   id: uv-lock

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
    -   id: ruff-check
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
    -   id: interrogate
        args: [ refire ]
        pass_filenames: false

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
    -   id: mypy
