name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        uv sync --locked --all-extras

    - name: Lint & Format with ruff
      run: |
        uv run ruff check .
        uv run ruff format --check

    - name: Check docstrings
      run: |
        uv run interrogate refire

    - name: Test with pytest
      run: |
        uv run pytest
